# baseURL = 'https://mikirov.github.io/orchid-bnb/'
baseURL = "https://blueorchidsuite.info/"

languageCode = 'en-us'
title = 'Orchid Suites'
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]
enableRobotsTXT = true
enableEmoji = true
publishDir = "public"
resourceDir = "public/resources"

theme = 'gallery'


[params]
  defaultTheme = "dark"
  description = "Orchid Suites"
  title = "Orchid Suites"
  [params.author]
    email = "me@mikirov.xyz"
    name = "Mihail Kirov"
  [params.socialIcons]
    phone = "tel:+359877812720"
    email = "mailto:veliosbg@gmail.com"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"

[services]
  [services.rss]
    limit = 100